import Header from "@/components/Header";
import Providers from "@/components/providers";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Redit Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
          <div className="container mx-auto px-4 max-w-6xl">
            <Header />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
